/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiPortal;

//import uiPortal.Bank.BankLandingPage;
import uiPortal.Bank.BankLandingPage;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import profile.bank.BankPerson;
import profile.justiceDepartment.JusticeDepartmentEmployee;
import uiDonor.DonorLandingPage;
import uiPortal.Bank.BankEmployeePanel;
import uiPortal.NGO.NGOLandingPage;
import uiPortal.justiceDepartment.JusticeDepartmentEmployeePanel;
import utilities.Constants;
import uiPortal.justiceDepartment.JusticeDepartmentLandingPage;
import uiReceiver.ReceiverAssignCause;
import uiReceiver.ReceiverLandingPage;

/**
 *
 * @author abhis
 */
public class LandingPageFrame extends javax.swing.JFrame {
    private String loggedInUser;
    /**
     * Creates new form LandingPageFrame
     */
    public LandingPageFrame(String loggedInUser) {  
        initComponents();        
        validateRole(loggedInUser);
        this.loggedInUser = loggedInUser;
    }
    
    public LandingPageFrame(JusticeDepartmentEmployee justiceDepartmentEmp) {
        initComponents();
        this.loggedInUser = justiceDepartmentEmp.getFirstName() + " " + justiceDepartmentEmp.getLastName();
        setJusticeLoginFrame();
        setJusticeLandingPage(justiceDepartmentEmp.getEmpType(), justiceDepartmentEmp);
    }
    
    public LandingPageFrame(BankPerson bp) {
        initComponents();
        this.loggedInUser = bp.getFirstName() + " " + bp.getLastName();
        setBankLoginFrame();
        setBankLandingPage(bp.getEmpType(), bp);
    }
    
    private void setJusticeLandingPage(String empType, JusticeDepartmentEmployee justiceDepartmentEmp) {
        switch(empType) {
            case "ADMIN":
                JusticeDepartmentLandingPage justiceDepartmentLandingPage = new JusticeDepartmentLandingPage(justiceDepartmentEmp);
                jSplitPane.setRightComponent(justiceDepartmentLandingPage);
                break;
            case "EMPLOYEE":
                JusticeDepartmentEmployeePanel justiceDepartmentEmployeePanel = new JusticeDepartmentEmployeePanel();
                jSplitPane.setRightComponent(justiceDepartmentEmployeePanel);
                break;
        } 
    }
    
    private void setBankLandingPage(String empType, BankPerson bp) {
        switch(empType) {
            case "ADMIN":
                //BankLandingPage justiceDepartmentLandingPage = new JusticeDepartmentLandingPage(justiceDepartmentEmp);
                BankLandingPage bankLandingPage = new BankLandingPage(bp);
                jSplitPane.setRightComponent(bankLandingPage);
                break;
            case "EMPLOYEE":
                BankEmployeePanel bankEmployeePanel = new BankEmployeePanel();
                jSplitPane.setRightComponent(bankEmployeePanel);
                break;
        } 
    }

    
    private void setJusticeLoginFrame() {
        btnNGOLink.setVisible(false);
        btnBankLink.setVisible(false);
        btnServiceLink.setVisible(false);
        btnJusticeLink.setVisible(false);
    }
    
    private void setBankLoginFrame(){
        btnNGOLink.setVisible(false);
        btnBankLink.setVisible(false);
        btnServiceLink.setVisible(false);
        btnJusticeLink.setVisible(false);
    }
           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnNGOLink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnServiceLink = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnBankLink = new javax.swing.JButton();
        btnJusticeLink = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNGOLink.setText("NGO");
        btnNGOLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOLinkActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Welcome Sys Admin");

        btnServiceLink.setText("Service Provider");
        btnServiceLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceLinkActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 51, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBankLink.setText("BANK");
        btnBankLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankLinkActionPerformed(evt);
            }
        });

        btnJusticeLink.setText("JUSTICE DEPT.");
        btnJusticeLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJusticeLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNGOLink, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBankLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJusticeLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnServiceLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBankLink, btnJusticeLink, btnNGOLink, btnServiceLink});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnNGOLink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBankLink)
                .addGap(18, 18, 18)
                .addComponent(btnJusticeLink)
                .addGap(18, 18, 18)
                .addComponent(btnServiceLink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnLogout))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBankLink, btnJusticeLink, btnNGOLink, btnServiceLink});

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        dispose();
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setTitle("Dashboard");
        loginScreen.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNGOLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOLinkActionPerformed
        // TODO add your handling code here:
        NGOLandingPage ngoLandingPage = new NGOLandingPage(loggedInUser);
        jSplitPane.setRightComponent(ngoLandingPage);
    }//GEN-LAST:event_btnNGOLinkActionPerformed

    private void btnServiceLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiceLinkActionPerformed

    private void btnBankLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankLinkActionPerformed
        // TODO add your handling code here:
        BankLandingPage bankLandingPage = new BankLandingPage();
        jSplitPane.setRightComponent(bankLandingPage);
    }//GEN-LAST:event_btnBankLinkActionPerformed

    private void btnJusticeLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJusticeLinkActionPerformed
        // TODO add your handling code here:
        JusticeDepartmentLandingPage justiceDepartmentLandingPage = new JusticeDepartmentLandingPage();
        jSplitPane.setRightComponent(justiceDepartmentLandingPage);
    }//GEN-LAST:event_btnJusticeLinkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.out.println("NONE");
    }                                           




    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LandingPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LandingPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LandingPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LandingPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LandingPageFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBankLink;
    private javax.swing.JButton btnJusticeLink;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNGOLink;
    private javax.swing.JButton btnServiceLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables

    public void validateRole(String loggedInUser){
        

        
        if(loggedInUser != null){
            
            System.out.println(loggedInUser);

            btnBankLink.setVisible(false);
            btnJusticeLink.setVisible(false);

            // btnBankLink.setVisible(false);
           // btnJusticeLink.setVisible(false);
            btnServiceLink.setVisible(false);
            jLabel1.setText(loggedInUser);
            jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel1.setVerticalAlignment(SwingConstants.CENTER);            
        }
        try{
            if(loggedInUser.contains("Receiver")){
                btnBankLink.setVisible(false);
                btnJusticeLink.setVisible(false);
                jLabel1.setText(loggedInUser.split("-")[0].trim());
                // btnBankLink.setVisible(false);
               // btnJusticeLink.setVisible(false);
                btnServiceLink.setVisible(false);
                btnNGOLink.setVisible(false);
                ReceiverLandingPage receiverLandingPage = new ReceiverLandingPage(loggedInUser);
                jSplitPane.setRightComponent(receiverLandingPage);            
                return;
            }
            if(loggedInUser.contains("Donor")){
                btnBankLink.setVisible(false);
                btnJusticeLink.setVisible(false);
                jLabel1.setText(loggedInUser.split("-")[0].trim());
                // btnBankLink.setVisible(false);
               // btnJusticeLink.setVisible(false);
                btnServiceLink.setVisible(false);
                btnNGOLink.setVisible(false);
                DonorLandingPage donorLandingPage = new DonorLandingPage(loggedInUser);
                jSplitPane.setRightComponent(donorLandingPage);            
                return;
                
                
            }                  
        }catch(Exception e){
            System.out.println("WRONG");
        }
  
        
        
    } 

}
