/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiDonor;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import model.causes.Cause;
import model.causes.CauseDirectory;
import model.causeticket.CauseTicket;
import model.causeticket.CauseTicketDirectory;
import model.justiceTicket.JusticeTicket;
import model.justiceTicket.JusticeTicketDirectory;
import profile.Receiver.Receiver;
import profile.Receiver.ReceiverDirectory;
import profile.donor.Donor;
import profile.donor.DonorDirectory;
import profile.justiceDepartment.JusticeDepartmentEmployee;
import profile.justiceDepartment.JusticeDepartmentEmployeeDirectory;
import utilities.Constants;

/**
 *
 * @author abhis
 */
public class DonorTrackCause extends javax.swing.JPanel {

    /**
     * Creates new form DonorTrackCause
     */
    CauseDirectory causeDirectory;
    Cause cause;    
    CauseTicketDirectory causeTicketDirectory;
    CauseTicket causeTicket;     
    CauseTicket justiceCauseTicket;
    private String loggedInUser; 
    DonorDirectory donorDirectory;
    Donor donor;    
    
    private int donorID;  
    
    public DonorTrackCause(int donorID) throws SQLException {
        initComponents();
        this.donorID = donorID;
        this.donorDirectory = new DonorDirectory(donor);
        this.causeTicketDirectory = new CauseTicketDirectory(causeTicket);
        System.out.println("TRACKERRR "+donorID);
        popDonorTrackingTable(donorDirectory.popDonorTrackingTable(donorID));
        System.out.println(donorID+" pop table  ");
        btnOrangeFlag.setVisible(false);
        jProgressBar1.setVisible(false);
        btnRedFlag.setVisible(false);
        btnTrackJusticeTkt.setVisible(false);
        panelJudiciary.setVisible(false);
    }
    
    
//    public void()
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCause = new javax.swing.JTable();
        btnTrackCause = new javax.swing.JButton();
        txtTracker = new javax.swing.JPanel();
        txtDate1 = new javax.swing.JLabel();
        txtDate2 = new javax.swing.JLabel();
        txtDate3 = new javax.swing.JLabel();
        txtDate4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        panelJudiciary = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblUpdateDate = new javax.swing.JLabel();
        lblCreateDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtCreated = new javax.swing.JLabel();
        txtCreated2 = new javax.swing.JLabel();
        txtCreated1 = new javax.swing.JLabel();
        txtCreated3 = new javax.swing.JLabel();
        btnRedFlag = new javax.swing.JButton();
        btnTrackJusticeTkt = new javax.swing.JButton();
        btnOrangeFlag = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCause.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NGO Organisation", "Cause Name", "Cause Description", "Receiving Category", "Country"
            }
        ));
        jScrollPane1.setViewportView(tblCause);

        btnTrackCause.setText("Track ");
        btnTrackCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackCauseActionPerformed(evt);
            }
        });

        txtTracker.setBackground(new java.awt.Color(255, 255, 255));

        panelJudiciary.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Status");

        jLabel2.setText("Updated Date");

        jLabel3.setText("Created Date");

        lblStatus.setText("jLabel4");

        lblUpdateDate.setText("jLabel5");

        lblCreateDate.setText("jLabel6");

        jLabel4.setText("Email");

        lblEmail.setText("jLabel5");

        javax.swing.GroupLayout panelJudiciaryLayout = new javax.swing.GroupLayout(panelJudiciary);
        panelJudiciary.setLayout(panelJudiciaryLayout);
        panelJudiciaryLayout.setHorizontalGroup(
            panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudiciaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addGroup(panelJudiciaryLayout.createSequentialGroup()
                        .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(lblUpdateDate)
                            .addComponent(lblCreateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelJudiciaryLayout.setVerticalGroup(
            panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudiciaryLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUpdateDate))
                .addGap(18, 18, 18)
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCreateDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJudiciaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout txtTrackerLayout = new javax.swing.GroupLayout(txtTracker);
        txtTracker.setLayout(txtTrackerLayout);
        txtTrackerLayout.setHorizontalGroup(
            txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtTrackerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDate3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJudiciary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        txtTrackerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDate1, txtDate2, txtDate3, txtDate4});

        txtTrackerLayout.setVerticalGroup(
            txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtTrackerLayout.createSequentialGroup()
                .addGroup(txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelJudiciary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtTrackerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(txtTrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtTrackerLayout.createSequentialGroup()
                                .addComponent(txtDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)
                                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(txtDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTrackerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDate1, txtDate2, txtDate3, txtDate4});

        txtCreated.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtCreated2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtCreated1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtCreated3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnRedFlag.setText("Raise Red Flag");
        btnRedFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedFlagActionPerformed(evt);
            }
        });

        btnTrackJusticeTkt.setText("Track JusticeTicket");
        btnTrackJusticeTkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackJusticeTktActionPerformed(evt);
            }
        });

        btnOrangeFlag.setText("Raise Orange Flag");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreated3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreated2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreated1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTracker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTrackCause)
                        .addGap(18, 18, 18)
                        .addComponent(btnRedFlag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrackJusticeTkt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrangeFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCreated, txtCreated1, txtCreated2, txtCreated3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrackCause)
                    .addComponent(btnRedFlag)
                    .addComponent(btnTrackJusticeTkt)
                    .addComponent(btnOrangeFlag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTracker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreated1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtCreated2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtCreated3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCreated, txtCreated1, txtCreated2, txtCreated3});

    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackCauseActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblCause.getSelectedRow();
        panelJudiciary.setVisible(false);
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            DefaultTableModel m2 = (DefaultTableModel)tblCause.getModel();
            Cause SelectedRecords = (Cause) m2.getValueAt(SelectedRow, 0);
            System.out.println("CAUSE IDDDDD "+SelectedRecords.getCauseId());
            JOptionPane.showMessageDialog(this,"The Exact location of your funds is given below");
            try {
                ArrayList<CauseTicket> trackCauses = causeTicketDirectory.trackCause(donorID);
                for(CauseTicket causetix : trackCauses){
                    if(causetix.getReceiverId()==SelectedRecords.getRecId()){
                        Date createdDate = causetix.getCreatedDate();
                        System.out.println(createdDate+"YOOOOOOOOOOOOOOOO");
                        checkForJusticeDeptTickets(causetix);
                        Date moneyDonorCountry = causetix.getMoneyDonorCountry();
                        Date moneyReceiverCountry = causetix.getMoneyReceiverCountry();
                        Date moneyReceived = causetix.getMoneyReceived();
                        System.out.println(moneyDonorCountry+"YOOOOOOOOOOOOOOOO");                             
                        int MY_MINIMUM = 0;
                        int MY_MAXIMUM = 100;
                        int check = 0;
//                        jPanel1.setVisible(true);

                        jProgressBar1.setVisible(true);
                        jProgressBar1.setMinimum(MY_MINIMUM);
                        jProgressBar1.setMaximum(MY_MAXIMUM);
                        jProgressBar1.setValue(100);
                        jProgressBar1.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
                        jProgressBar1.setOrientation(JProgressBar.VERTICAL);
                        
                        if(moneyReceived!=null){
                            check+=1;
//                            jProgressBar1.setString("Your funds are almost there");
                            txtCreated.setText("<html>Your Funds have reached the right people on \n Thank you for using HelpingHands</html>");
                            txtDate1.setText(moneyReceived.toString());          
                            
                        }                               
                        if(moneyReceiverCountry!=null){
                            check+=1;
//                            jProgressBar1.setString("Your funds are almost there");
                            txtCreated1.setText("<html>Your Funds were processed by the bank in \n "+ causetix.getReceivingCountry() +" and will be in the hands of the benificiary soon</html>");
                            txtDate2.setText(moneyReceiverCountry.toString());                            
                       
                        }                                
                        if(moneyDonorCountry!=null){
                            check+=1;
//                            jProgressBar1.setString("Your funds are almost there");
                            txtCreated2.setText("<html>Your Funds were Processed in \n "+causetix.getDonorCountry()+" and will be tracked by the Receiving Country Bank authorities soon</html>");
                            txtDate3.setText(moneyDonorCountry.toString());
                            
                        }    
                        if(createdDate!=null){
                            check+=1;                            
//                            jProgressBar1.setString("funds almost there");
                            txtCreated3.setText("<html>Your Funds were Initiated on</html>");
                            txtDate4.setText( createdDate.toString());
                            final String html = "<html><body style='width: %1spx'>%1s";
               
                        }
                    
                        if(check==1){
                            jProgressBar1.setValue(25);
                            return;
                        }
                        if(check==2){
                            jProgressBar1.setValue(50);                            
                            return;
                        }
                        if(check==3){
                            jProgressBar1.setValue(75);                            
                            return;
                        }
                        if(check==4){
                            jProgressBar1.setValue(100);                            
                            return;
                        }
                        

                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(DonorTrackCause.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_btnTrackCauseActionPerformed

    private void btnRedFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedFlagActionPerformed
        // TODO add your handling code here:
        if (justiceCauseTicket != null) {
            int causeTktId = justiceCauseTicket.getTktId();
            String country = justiceCauseTicket.getDonorCountry();
         if ((causeTktId == 0 || causeTktId > 0) && country != null && !country.trim().equals("")) {
             Date date = new Date();
             JusticeTicket jTicket = new JusticeTicket(causeTktId, date, Constants.justiceTicketStatus.get("new"), country, date);
             JusticeTicketDirectory jtktDirectory = new JusticeTicketDirectory(jTicket); 
             try {
                jtktDirectory.createJusticeTicket();
                JOptionPane.showMessageDialog(this, "Justice ticket has been created");
                setJusticeTicketData();
             } catch (Exception e) {
                 System.out.println(e);
             }
             
         }
        }

        // System.out.println("justice country "+jTracCause.getCountry());
        
    }//GEN-LAST:event_btnRedFlagActionPerformed

    private void btnTrackJusticeTktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackJusticeTktActionPerformed
        // TODO add your handling code here:
        setJusticeTicketData();
    }//GEN-LAST:event_btnTrackJusticeTktActionPerformed
    
    private void setJusticeTicketData() {
        if (justiceCauseTicket != null) {
            JusticeTicket jtkt  = checkIfJusticeTicketExist(justiceCauseTicket);
            lblStatus.setText(jtkt.getjTktStatus());
             DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd"); 
            if (jtkt.getCreatedDate() != null) {
                lblCreateDate.setText(formatter.format(jtkt.getCreatedDate()));
                 } else {
                     lblCreateDate.setText("NA");
                 }
                 if (jtkt.getUpdatedDate() != null) {
                        lblUpdateDate.setText(formatter.format(jtkt.getUpdatedDate()));
                 } else {
                     lblUpdateDate.setText("NA");
                 } 
            setFontColorForJusticeStatus(jtkt.getjTktStatus());
            if (jtkt != null && !jtkt.getjTktStatus().trim().equals("NEW")) {
                JusticeDepartmentEmployeeDirectory jdEmpDirectory = new JusticeDepartmentEmployeeDirectory(null);
                JusticeDepartmentEmployee jDemp = null;
                try {
                    int jEmpId = jtkt.getjEmpId();
                    if (jEmpId > 0) {
                        jDemp = jdEmpDirectory.fetchEmployeeById(jEmpId); 
                        if (jDemp != null) {
                            lblEmail.setText(jDemp.getEmail());
                            lblEmail.setVisible(true);
                        }
                    }
                   
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                 lblEmail.setText("NA");
            }
            panelJudiciary.setVisible(true);
        }
    }
    
            
           private void setFontColorForJusticeStatus(String status) {
            switch (status) {
                case "NEW":
                    Color newBlue = new Color(102, 255,255);
                    lblStatus.setForeground(newBlue);
                    break;
                case "ASSIGNED":
                    Color newOrange = new Color(255, 153,51);
                    lblStatus.setForeground(newOrange);
                    break;
                case "WIP":
                    Color  newLeafColor= new Color(255, 153,0);
                    lblStatus.setForeground(newLeafColor);
                    break;
                case "RESOLVED":
                    Color  success= new Color(51, 153,0);
                    lblStatus.setForeground(success);
                    break;
                default:
                    throw new AssertionError();
            
        }
    }
    private void popDonorTrackingTable(ArrayList<Cause> donorTable) throws SQLException {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel)tblCause.getModel();
        model.setRowCount(0);
        for(Cause cause: donorTable){
            Object[] row = new Object[6];
            row[0] = cause;
            row[1] = cause.getCauseName();
            row[2] = cause.getCauseDesc();
            row[3] = cause.getRecCategory();
            row[4] = cause.getCountry();                                     
            model.addRow(row);
        }
    }
    
    private void checkForJusticeDeptTickets( CauseTicket causetix) {
        if (causetix != null) {
            JusticeTicket  jtkt = checkIfJusticeTicketExist(causetix);
            if (jtkt != null) {
                 btnTrackJusticeTkt.setVisible(true);
                 btnRedFlag.setVisible(false);
                 btnOrangeFlag.setVisible(false);
                  justiceCauseTicket = causetix;
            } else {
              if (causetix.getMoneyDonorCountry() == null) { 
                           Date today = new Date();
             Date createdDate = causetix.getCreatedDate();
             long timeDiff = Math.abs(today.getTime() - createdDate.getTime());
             long daysDiff = TimeUnit.DAYS.convert(timeDiff, TimeUnit.MILLISECONDS);
             if (daysDiff > 10 || daysDiff == 10) {
                 btnTrackJusticeTkt.setVisible(false);
                 btnRedFlag.setVisible(true);
                 btnRedFlag.setText("Raise Red Flag");
                 btnOrangeFlag.setVisible(false);
                 justiceCauseTicket = causetix;
             }
              } else if (causetix.getMoneyReceiverCountry()== null) {
              Date today = new Date();
             Date createdDate = causetix.getCreatedDate();
             long timeDiff = Math.abs(today.getTime() - createdDate.getTime());
             long daysDiff = TimeUnit.DAYS.convert(timeDiff, TimeUnit.MILLISECONDS);
             if (daysDiff > 10 || daysDiff == 10) {
                 btnTrackJusticeTkt.setVisible(false);
                 btnRedFlag.setVisible(false);
                 btnOrangeFlag.setVisible(true);
                 justiceCauseTicket = causetix;
             }
              } else {
                 btnTrackJusticeTkt.setVisible(false);
                 btnRedFlag.setVisible(false);
              }


                }
        }
    }
    
    
    private JusticeTicket checkIfJusticeTicketExist(CauseTicket causetix) {
        JusticeTicket  jtkt = null;
        JusticeTicketDirectory jTktDirectory = new JusticeTicketDirectory(null);
        try {
             jtkt = jTktDirectory.fetchJusticeTicketByCauseId(causetix.getTktId());
        } catch (Exception e) {
            System.out.println(e);
        }
        return jtkt;
                
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrangeFlag;
    private javax.swing.JButton btnRedFlag;
    private javax.swing.JButton btnTrackCause;
    private javax.swing.JButton btnTrackJusticeTkt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUpdateDate;
    private javax.swing.JPanel panelJudiciary;
    private javax.swing.JTable tblCause;
    private javax.swing.JLabel txtCreated;
    private javax.swing.JLabel txtCreated1;
    private javax.swing.JLabel txtCreated2;
    private javax.swing.JLabel txtCreated3;
    private javax.swing.JLabel txtDate1;
    private javax.swing.JLabel txtDate2;
    private javax.swing.JLabel txtDate3;
    private javax.swing.JLabel txtDate4;
    private javax.swing.JPanel txtTracker;
    // End of variables declaration//GEN-END:variables
}
