/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiPortal.Bank;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.causeBankTrack.BankAssignTicket;
import model.causeBankTrack.BankAssignTicketDirectory;
import model.causeBankTrack.BankEmployeeTicket;
import model.causeBankTrack.BankTicket;
import model.causeBankTrack.BankTicketDirectory;
import model.causes.Cause;
import model.causes.CauseDirectory;
import model.causeticket.CauseTicket;
import model.causeticket.CauseTicketDirectory;
import profile.bank.BankPerson;
import profile.bank.BankPersonDirectory;
import utilities.Constants;

/**
 *
 * @author HP
 */
public class BankAssignTicketPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankAssignTicket
     */
    
    BankAssignTicketDirectory bankAssignTicketDirectory;
    BankAssignTicket bankAssignTicket;
    ArrayList<BankAssignTicket> allBankAssignTicket;
    ArrayList<BankEmployeeTicket> bankEmpTktList;
    BankPerson bankPerson;
    ArrayList<BankPerson> activeBankPersonList;
    BankPersonDirectory bankPersonDirectory; 
    
    String loggedInUserCountry = "";
    public BankAssignTicketPanel() throws SQLException {
        initComponents();
        
        this.bankPersonDirectory = new BankPersonDirectory(bankPerson);
        this.bankAssignTicketDirectory = new BankAssignTicketDirectory(bankAssignTicket);
        allBankAssignTicket = new ArrayList<BankAssignTicket>();
        populateBankAssignTable();
        bankEmpTktList = new ArrayList<BankEmployeeTicket>();
        fetchBankEmpTicketData();
        activeBankPersonList = new ArrayList<BankPerson>();
        populateBankEmpTable();
    }
    public BankAssignTicketPanel(BankPerson bankPerson) throws SQLException{
        initComponents();
        
        this.bankPersonDirectory = new BankPersonDirectory(bankPerson);
        this.bankAssignTicketDirectory = new BankAssignTicketDirectory(bankAssignTicket);
        allBankAssignTicket = new ArrayList<BankAssignTicket>();
        populateBankAssignTable();
        bankEmpTktList = new ArrayList<BankEmployeeTicket>();
        fetchBankEmpTicketData();
        activeBankPersonList = new ArrayList<BankPerson>();
        populateBankEmpTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void populateBankAssignTable(){
        
        DefaultTableModel model = (DefaultTableModel)tblAssignTicket.getModel();
        model.setRowCount(0);
        if (bankEmpTktList != null && !bankEmpTktList.isEmpty()) {
          for(BankEmployeeTicket bnkEmpTkt: bankEmpTktList){
            Object[] row = new Object[2];
            row[0] = bnkEmpTkt;
            row[1] = bnkEmpTkt.getCauseTicket().getCreatedDate();
            model.addRow(row);
        } 
        }

    }
    
    public void populateBankEmpTable() throws SQLException{
        
        DefaultTableModel model = (DefaultTableModel)tblEmployee.getModel();
        model.setRowCount(0);
        activeBankPersonList = bankPersonDirectory.populateActiveBp();
        
        for(BankPerson bankPerson: activeBankPersonList){
            Object[] row = new Object[6];
            //row[0] = bankPerson;
            if(bankPerson.getEmpType().equals("EMPLOYEE")){
                row[0] = bankPerson.getFirstName();
                row[1] = bankPerson.getLastName();
                row[2] = bankPerson.getEmail();
            }
            
            model.addRow(row);
            System.out.print("BANK PERSON"+bankPerson.getFirstName());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignTicket = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCauseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCreateDate = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tblAssignTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cause Name", "Create Date"
            }
        ));
        jScrollPane1.setViewportView(tblAssignTicket);

        jButton1.setText("Select Ticket");

        jButton2.setText("View Assigned");

        jButton3.setText("View Unassigned");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Assign Tickets to Bank Employees");

        jLabel2.setText("Cause Name");

        jLabel4.setText("Create Date");

        txtCreateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateDateActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last name", "Email Id"
            }
        ));
        jScrollPane2.setViewportView(tblEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCauseName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAssign)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCauseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssign)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateDateActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAssignActionPerformed
    private void fetchBankEmpTicketData(){
        BankTicketDirectory bnkDirectory = new BankTicketDirectory(null);
        ArrayList<BankTicket> allBankTickets = new ArrayList<BankTicket>();
        try {
            allBankTickets = bnkDirectory.fetchBankTicket();
            if(allBankTickets != null && !allBankTickets.isEmpty()) {
               bankEmpTktList = new ArrayList<BankEmployeeTicket>(); 
               for(BankTicket bnkTkt : allBankTickets) {
                   BankEmployeeTicket bnkEmpTkt = new BankEmployeeTicket(bnkTkt);
                   CauseTicket causeTicket = fetchCauseTicketData(bnkTkt.getCauseTkId());
                   if (causeTicket != null) {
                       bnkEmpTkt.setCauseTicket(causeTicket);
                       Cause cause = fetchCauseData(causeTicket.getCauseId());
                       if (cause != null) {
                           bnkEmpTkt.setCause(cause);
                       }
                   }
                   bankEmpTktList.add(bnkEmpTkt);
               }
               
               populateBankAssignTable();
            }
        } catch(Exception e){
            System.out.println(e);
        }
        
    }
    
        private Cause fetchCauseData(int causeId) {
        Cause cause = null;
        try {
           CauseDirectory causeDirectory =  new CauseDirectory(null); 
           cause = causeDirectory.fetchCauseById(causeId);
        } catch (Exception e) {
            System.out.println(e);
        }
        return cause;
    }
    
        private CauseTicket fetchCauseTicketData(int causeTicketId) {
        CauseTicket causeTicket= null;
        try {
            CauseTicketDirectory causeTicketDirectory = new CauseTicketDirectory(null);
            causeTicket = causeTicketDirectory.fetchCauseTicketData(causeTicketId);
        } catch (Exception e) {
            System.out.println(e);
        }
        return causeTicket;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAssignTicket;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtCauseName;
    private javax.swing.JTextField txtCreateDate;
    // End of variables declaration//GEN-END:variables
}
