/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiPortal.Bank;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import profile.bank.BankPerson;
import profile.bank.BankPersonDirectory;
import utilities.Constants;
import utilities.Validators;

/**
 *
 * @author Anvi Jain
 */
public class BankCreateUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankCreateUserPanel
     */
    int inValidForm = 0;
    private String loggedInUser;
    public BankCreateUserPanel() {
        initComponents();
        //dropdownCountry.setSelectedIndex(-1);
        setCountriesDropdown();
        setEmpTypeDropdown();
        
    }
    
    public BankCreateUserPanel(BankPerson bp){
        initComponents();
        //setCountriesDropdown();
        setPanelForUser(bp);
      
    }
    
    public void setPanelForUser(BankPerson bp){
        String userCountry = bp.getCountry();
        String userType = bp.getEmpType();
        ArrayList<String> countriesList = new ArrayList<String>();
        countriesList.addAll(Constants.donorCountries);
        countriesList.addAll(Constants.receivingCountries);
        
        /*
        for each country in the dropdown/constants 
        get a list of all countries
        match user to the country
        if country matches
        set the dropdown to that country
        */
        for (String country : countriesList )
        {
            if(userCountry.equals(country))
            {
                dropdownCountry.removeAllItems();
                dropdownCountry.addItem(userCountry);
                dropdownCountry.setEnabled(false);
            }
        }
        
        dropDownType.removeAllItems();
        dropDownType.addItem("EMPLOYEE");
        dropDownType.setEnabled(false);
        
    }
    
    
    public void setCountriesDropdown() {
        ArrayList<String> countriesList = new ArrayList<String>();
        countriesList.add("");
        countriesList.addAll(Constants.donorCountries);
        countriesList.addAll(Constants.receivingCountries);
        Vector<String> contryVector = new Vector<>(countriesList);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(contryVector);
        dropdownCountry.setModel(model);
    }
    
    public void setEmpTypeDropdown() {
        
        Vector<String> empTypeVector = new Vector<String>(Arrays.asList(Constants.empType));
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(empTypeVector);
        dropDownType.setModel(model);
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        dropDownType = new javax.swing.JComboBox<>();
        btnCreateUser = new javax.swing.JButton();
        dropdownCountry = new javax.swing.JComboBox<>();
        lblBankName = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblErrCountry = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblErrFirstName = new javax.swing.JLabel();
        lblErrLastName = new javax.swing.JLabel();
        lblErrType = new javax.swing.JLabel();
        lblErrConfirmPass = new javax.swing.JLabel();
        lblErrPassword = new javax.swing.JLabel();
        lblEmailErr = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Create User");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Email Id");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Bank Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Country");

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Type");

        dropDownType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownTypeActionPerformed(evt);
            }
        });

        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        dropdownCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownCountryActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Confirm Password");

        lblErrLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblErrLastNameFocusLost(evt);
            }
        });

        lblErrType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblErrTypeFocusLost(evt);
            }
        });

        lblErrConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblErrConfirmPassFocusLost(evt);
            }
        });

        lblErrPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblErrPasswordFocusLost(evt);
            }
        });

        lblEmailErr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblEmailErrFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFirstName)
                                        .addComponent(txtConfirmPassword)
                                        .addComponent(txtLastName)
                                        .addComponent(txtEmailId)
                                        .addComponent(dropdownCountry, 0, 154, Short.MAX_VALUE)
                                        .addComponent(dropDownType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPassword))))
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(lblErrFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrType, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(lblErrConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(lblErrPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(lblEmailErr, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(dropdownCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblErrLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(lblErrConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(dropDownType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblErrType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(btnCreateUser))
                            .addComponent(lblErrPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        Validators validator = new Validators();
        
        /*String selectedCountry = dropdownCountry.getSelectedItem().toString();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String emailId = txtEmailId.getText();
        String password = txtConfirmPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        String selectedEmployeeType = dropDownType.getSelectedItem().toString();
        String selctedCountry = dropdownCountry.getSelectedItem().toString();
        String bankName = Constants.bankDonorCountryList.get(selctedCountry);
        String type = dropDownType.getSelectedItem().toString();*/
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String emailId = txtEmailId.getText();
        String password = txtConfirmPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        String country = dropdownCountry.getSelectedItem().toString();
        System.out.print("Country selected:"+country);
        String selctedCountry = dropdownCountry.getSelectedItem().toString();
        String bankName = Constants.bankDonorCountryList.get(selctedCountry);
        String type = dropDownType.getSelectedItem().toString();
        
        if(firstName.isEmpty() || lastName.isEmpty() || emailId.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || selctedCountry.isEmpty() || type.isEmpty()){
            System.out.print("In if block");
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }
        
        
        
        
        BankPerson bankPerson = new BankPerson(firstName, lastName, emailId, password, type, bankName, true, country);
        
        System.out.println("SETTING Status "+bankPerson.isStatus());
        System.out.println("EMPPP TYPE"+bankPerson.getEmpType());
        BankPersonDirectory bankPersonDirectory = new BankPersonDirectory(bankPerson);
        bankPersonDirectory.addBankPerson();
        System.out.println("");
        JOptionPane.showMessageDialog(this, "Bank User Has been Created");
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void dropdownCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownCountryActionPerformed
        // TODO add your handling code here:
        
        String selctedCountry = dropdownCountry.getSelectedItem().toString();
        lblBankName.setText(Constants.bankDonorCountryList.get(selctedCountry));
        System.out.println("country selcted " + selctedCountry);
        //System.out.println("Bank name:"+Constants.bankDonorCountryList.get(selctedCountry));
    }//GEN-LAST:event_dropdownCountryActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void dropDownTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownTypeActionPerformed

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:
        //check it out
        String firstName = txtFirstName.getText();

        Validators validator = new Validators();
        String errorMsg = validator.validateName(firstName);

        if (errorMsg != null && !errorMsg.trim().equals("")) {
            lblErrFirstName.setText(errorMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrFirstName.setText("");
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void lblErrLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblErrLastNameFocusLost
        // TODO add your handling code here:
        String lastName = txtLastName.getText();

        Validators validator = new Validators();
        String errorMsg = validator.validateName(lastName);

        if (errorMsg != null && !errorMsg.trim().equals("")) {
            lblErrLastName.setText(errorMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                lblErrLastName.setText("");
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrLastName.setText("");
        }
        
    }//GEN-LAST:event_lblErrLastNameFocusLost

    private void lblEmailErrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblEmailErrFocusLost
        // TODO add your handling code here:
        String password = txtPassword.getText();
        Validators validator = new Validators();
        String errMsg = validator.validatePassword(password);

        if (errMsg != null && !errMsg.trim().equals("")) {
            lblEmailErr.setText(errMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                lblEmailErr.setText("");
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrPassword.setText("");
        }
    }//GEN-LAST:event_lblEmailErrFocusLost

    private void lblErrConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblErrConfirmPassFocusLost
        // TODO add your handling code here:
        String password = txtPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();

        Validators validator = new Validators();
        String errorMsg = validator.validateConfirmPassword(password, confirmPassword);

        if (errorMsg != null && !errorMsg.trim().equals("")) {
            lblErrConfirmPass.setText(errorMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                lblErrConfirmPass.setText("");
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrConfirmPass.setText("");
        }
    }//GEN-LAST:event_lblErrConfirmPassFocusLost

    private void lblErrTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblErrTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrTypeFocusLost

    private void lblErrPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblErrPasswordFocusLost
        // TODO add your handling code here:
        String password = txtPassword.getText();
        Validators validator = new Validators();
        String errMsg = validator.validatePassword(password);

        if (errMsg != null && !errMsg.trim().equals("")) {
            lblErrPassword.setText(errMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                lblErrPassword.setText("");
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrPassword.setText("");
        }
        
    }//GEN-LAST:event_lblErrPasswordFocusLost

    /*public void validateRole(String loggedInUser){

        if(loggedInUser != null){
            
            System.out.println(loggedInUser);
            countriesList.removeAllItems();
            countriesList.addItem(loggedInUser); 
            combobxOrganisation.setEnabled(false);
        }
        
        
    } */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> dropDownType;
    private javax.swing.JComboBox<String> dropdownCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblEmailErr;
    private javax.swing.JLabel lblErrConfirmPass;
    private javax.swing.JLabel lblErrCountry;
    private javax.swing.JLabel lblErrFirstName;
    private javax.swing.JLabel lblErrLastName;
    private javax.swing.JLabel lblErrPassword;
    private javax.swing.JLabel lblErrType;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
