/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiPortal.serviceprovider;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.causes.Cause;
import model.causes.CauseDirectory;
import profile.Receiver.Receiver;
import profile.Receiver.ReceiverDirectory;
import profile.serviceprovider.ServiceProvider;
import profile.serviceprovider.ServiceProviderDirectory;
import uiDonor.DonorAssignCause;
import uiReceiver.ReceiverAssignCause;
import utilities.Constants;

/**
 *
 * @author abhis
 */
public class ServiceProviderAssign extends javax.swing.JPanel {

    /**
     * Creates new form ServiceProviderAssign
     */
    private String loggedInUser;    
    CauseDirectory causeDirectory;
    Cause cause;
    ReceiverDirectory receiverDirectory;
    Receiver receiver;    
    ServiceProviderDirectory serviceProviderDirectory;
    ServiceProvider serviceProvider;    
    public ServiceProviderAssign(String loggedInUser) throws SQLException {
        initComponents();
        this.causeDirectory = new CauseDirectory(cause);        
        this.loggedInUser = loggedInUser;

        this.receiverDirectory = new ReceiverDirectory(receiver);
        this.serviceProviderDirectory = new ServiceProviderDirectory(serviceProvider);        
        if(loggedInUser==null){
            popServiceTable(serviceProviderDirectory.popServiceTable(null));
            btnSearch.setVisible(true);
            txtRequirement.setVisible(false);
            jLabel2.setVisible(false);
            btnAssignCause.setVisible(false);
        }else{
            popServiceTable(serviceProviderDirectory.popServiceTable(loggedInUser.split("-")[1].trim()));
            btnSearch.setVisible(false);
        }
        
        for(String item : Constants.ngoOrganisations){
            if(loggedInUser!=null){
                if(item.equals(loggedInUser.split("-")[1].trim())){
                     combobxCause.removeAllItems();
                     combobxCause.addItem(loggedInUser.split("-")[1].trim());
                     combobxCause.setEnabled(false);                        
                    }
                
            }
        }    
        for(String item : Constants.ngoOrganisations){       

            if(loggedInUser==null){
                System.out.println(item);                
                combobxCause.addItem(item);
            }

        }
        if(loggedInUser==null){
            combobxCause.setEnabled(true);
            combobxCause.setSelectedIndex(-1);    
        }
        
    }
    private void popServiceTable(ArrayList<Cause> receiverTable) throws SQLException {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel)tblCause.getModel();
        model.setRowCount(0);
        for(Cause cause: receiverTable){
            Object[] row = new Object[6];
            row[0] = cause;
            row[1] = cause.getCauseName();
            row[2] = cause.getCauseDesc();
            row[3] = cause.getRecCategory();
            row[4] = cause.getCountry();                                     
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssignCause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCause = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        combobxCause = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRequirement = new javax.swing.JTextField();

        btnAssignCause.setText("Assign Cause");
        btnAssignCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignCauseActionPerformed(evt);
            }
        });

        tblCause.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NGO Organisation", "Cause Name", "Cause Description", "Receiving Category", "Country"
            }
        ));
        jScrollPane1.setViewportView(tblCause);

        btnSearch.setText("Search Cause");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        combobxCause.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combobxCauseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                combobxCauseFocusLost(evt);
            }
        });
        combobxCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobxCauseActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Cause");

        jLabel2.setText("Community Requirement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(combobxCause, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAssignCause)))
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobxCause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignCause)
                    .addComponent(jLabel2)
                    .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignCauseActionPerformed
        // TODO add your handling code here:
        ArrayList<Receiver> allReceivers = null;
        String cause = combobxCause.getSelectedItem().toString();//loggedInUser.split("-")[1].trim();
        if(loggedInUser!=null){
            try {            
                allReceivers = serviceProviderDirectory.getService(loggedInUser.split("-")[0].trim());
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(ServiceProviderAssign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }else{
            try {
                ArrayList<Receiver> receiver = serviceProviderDirectory.getUser(cause);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(ServiceProviderAssign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        int SelectedRow = tblCause.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            if(txtRequirement.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Input a requirement");       
                
                return;
            }
            DefaultTableModel m2 = (DefaultTableModel)tblCause.getModel();
            Cause SelectedRecords = (Cause) m2.getValueAt(SelectedRow, 0);
            System.out.println("CAUSE IDDDDD "+SelectedRecords.getCauseId());
            JOptionPane.showMessageDialog(this,"Thank you for Choosing Helping Hands \n Your Cause matters");
            String country = SelectedRecords.getCountry();
            String category = SelectedRecords.getRecCategory();
            String recCause = SelectedRecords.getCauseName();
            int causeId = SelectedRecords.getCauseId();
            int  recId = Integer.valueOf(allReceivers.get(0).getId());
            int req = Integer.valueOf(txtRequirement.getText());
            serviceProviderDirectory.updateCause(recId, causeId, req);
            txtRequirement.setText("");
            //            receiverDirectory.updateCause(Integer.valueOf(resultSet.getString("ID")), Integer.valueOf(SelectedRecords.getCauseId()));
        }


//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(ReceiverAssignCause.class.getName()).log(Level.SEVERE, null, ex);
//            }

    }//GEN-LAST:event_btnAssignCauseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String cause1 = combobxCause.getSelectedItem().toString();
        try {
            popServiceTable(serviceProviderDirectory.popServiceTable(cause1));
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(DonorAssignCause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void combobxCauseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combobxCauseFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_combobxCauseFocusGained

    private void combobxCauseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combobxCauseFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_combobxCauseFocusLost

    private void combobxCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobxCauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobxCauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignCause;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> combobxCause;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCause;
    private javax.swing.JTextField txtRequirement;
    // End of variables declaration//GEN-END:variables
}
