/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiPortal.NGO;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.causes.Cause;
import model.causes.CauseDirectory;
import utilities.Constants;
import utilities.Validators;
/**
 *
 * @author abhis
 */
public class NGOCreateCausePanel extends javax.swing.JPanel {
    private String loggedInUser;
    int inValidForm = 0;
    /**
     * Creates new form NGOCreateCausePanel
     */
    public NGOCreateCausePanel(String loggedInUser) {
        initComponents();
        
        for (String item :Constants.receivingCountries) {
            combobxCountry.addItem(item);
        }
        
        for(String item : Constants.ngoOrganisations){
            combobxOrganisation.addItem(item);
        }
        
        for(String item : Constants.receivingType){
            combobxCategory.addItem(item);
        }
        
        if(loggedInUser != null){
            validateRole(loggedInUser);
            combobxCountry.setSelectedIndex(-1);      
            combobxCategory.setSelectedIndex(-1);                 
        }else{
            combobxOrganisation.setSelectedIndex(-1);        
            combobxCountry.setSelectedIndex(-1);      
            combobxCategory.setSelectedIndex(-1);            
        }       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobxOrganisation = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnCreateCause = new javax.swing.JButton();
        combobxCountry = new javax.swing.JComboBox<>();
        combobxCategory = new javax.swing.JComboBox<>();
        lblErrFirstName = new javax.swing.JLabel();
        lblErrFirstName1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Organisation:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Description:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Country:");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnCreateCause.setBackground(new java.awt.Color(0, 153, 0));
        btnCreateCause.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateCause.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateCause.setText("Create");
        btnCreateCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCauseActionPerformed(evt);
            }
        });

        lblErrFirstName.setForeground(new java.awt.Color(153, 0, 0));

        lblErrFirstName1.setForeground(new java.awt.Color(153, 0, 0));
        lblErrFirstName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblErrFirstName1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateCause)
                    .addComponent(combobxOrganisation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(combobxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combobxCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrFirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combobxOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(combobxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combobxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCreateCause)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCauseActionPerformed
        // TODO add your handling code here:


        String name = txtName.getText();
        String description = txtDescription.getText();

        Validators validator = new Validators();
        if(name.equals("") || description.equals("") || combobxCategory.getSelectedIndex() == -1 || 
                combobxOrganisation.getSelectedIndex() == -1 || combobxCountry.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }
        String organisation = combobxOrganisation.getSelectedItem().toString();
        String country = combobxCountry.getSelectedItem().toString();        
        String category = combobxCategory.getSelectedItem().toString();
        Cause cause = new Cause(name,description,organisation,category,country,false);
        CauseDirectory causeDirectory = new CauseDirectory(cause);
        causeDirectory.addCause();
        txtName.setText("");
        txtDescription.setText("");
        combobxOrganisation.setSelectedIndex(-1);
        combobxCountry.setSelectedIndex(-1);
        combobxCategory.setSelectedIndex(-1);
        JOptionPane.showMessageDialog(this, "Cause Has been Created");

    }//GEN-LAST:event_btnCreateCauseActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        String firstName = txtName.getText();

        Validators validator = new Validators();
        String errorMsg = validator.validateName(firstName);

        if (errorMsg != null && !errorMsg.trim().equals("")) {
            lblErrFirstName.setText(errorMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrFirstName.setText("");
        }                
    }//GEN-LAST:event_txtNameFocusLost

    private void lblErrFirstName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblErrFirstName1FocusLost
        // TODO add your handling code here:
        String firstName = txtDescription.getText();

        Validators validator = new Validators();
        String errorMsg = validator.validateName(firstName);

        if (errorMsg != null && !errorMsg.trim().equals("")) {
            lblErrFirstName.setText(errorMsg);
            inValidForm += 1;
        } else {
            if (inValidForm > 0) {
                inValidForm -= 1;
            }
        }

        if (inValidForm == 0) {
            lblErrFirstName.setText("");
        }                
    }//GEN-LAST:event_lblErrFirstName1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCause;
    private javax.swing.JComboBox<String> combobxCategory;
    private javax.swing.JComboBox<String> combobxCountry;
    private javax.swing.JComboBox<String> combobxOrganisation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrFirstName;
    private javax.swing.JLabel lblErrFirstName1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    public void validateRole(String loggedInUser){

        if(loggedInUser != null){
            
            System.out.println(loggedInUser);
            combobxOrganisation.removeAllItems();
            combobxOrganisation.addItem(loggedInUser); 
            combobxOrganisation.setEnabled(false);
        }
        
        
    } 

}
