/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiPortal.NGO;

import utilities.DbConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author abhis
 */
public class NGOLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form NGOLandingPage
     */
    public NGOLandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreateCause = new javax.swing.JButton();
        btnViewCause = new javax.swing.JButton();
        cardLayoutPanel = new javax.swing.JPanel();

        btnCreateCause.setText("Create Cause");
        btnCreateCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCauseActionPerformed(evt);
            }
        });

        btnViewCause.setText("View Cause");
        btnViewCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(btnCreateCause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCause)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCause)
                    .addComponent(btnViewCause))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardLayoutPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardLayoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCauseActionPerformed
        // TODO add your handling code here:
        NGOCreateCausePanel ngoCreateCausePanel = new NGOCreateCausePanel();
        cardLayoutPanel.removeAll();
        cardLayoutPanel.add(ngoCreateCausePanel);
        cardLayoutPanel.repaint();
        cardLayoutPanel.revalidate();
    }//GEN-LAST:event_btnCreateCauseActionPerformed

    private void btnViewCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCauseActionPerformed
        // TODO add your handling code here:
        NGOViewCausePanel ngoViewCausePanel;
        try {
            ngoViewCausePanel = new NGOViewCausePanel();
            cardLayoutPanel.removeAll();
            cardLayoutPanel.add(ngoViewCausePanel);
            cardLayoutPanel.repaint();
            cardLayoutPanel.revalidate();            
        } catch (SQLException ex) {
            Logger.getLogger(NGOLandingPage.class.getName()).log(Level.SEVERE, null, ex);
        }

                
    }//GEN-LAST:event_btnViewCauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCause;
    private javax.swing.JButton btnViewCause;
    private javax.swing.JPanel cardLayoutPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
